version: "3.9"
services:
  db:
    image: "postgres:14.1-alpine"
    container_name: "postgres_timeforemost"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Postgres
      - POSTGRES_DB=timeforemost_db
