//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetForemost.SharedKernel.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetForemost.SharedKernel.Properties.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a api key sent had an invalid format.
        /// </summary>
        public static string ApikeyInvalidFormat {
            get {
                return ResourceManager.GetString("ApikeyInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a api key sent does not found.
        /// </summary>
        public static string ApiKeyNotFound {
            get {
                return ResourceManager.GetString("ApiKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The benefit sent [id] does not found.
        /// </summary>
        public static string BenefitIdNotFound {
            get {
                return ResourceManager.GetString("BenefitIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The block time tracking not exist..
        /// </summary>
        public static string BlockTimeTrackingNotExist {
            get {
                return ResourceManager.GetString("BlockTimeTrackingNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The city sent does not found.
        /// </summary>
        public static string CityNotFound {
            get {
                return ResourceManager.GetString("CityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The company sent does not found.
        /// </summary>
        public static string CompanyNotFound {
            get {
                return ResourceManager.GetString("CompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Does not have a registered company.
        /// </summary>
        public static string CompanyNotRegistered {
            get {
                return ResourceManager.GetString("CompanyNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The company does not have a settings created.
        /// </summary>
        public static string CompanySettingsNotFound {
            get {
                return ResourceManager.GetString("CompanySettingsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The company user specified not found.
        /// </summary>
        public static string CompanyUserNotFound {
            get {
                return ResourceManager.GetString("CompanyUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The company user specified with the ID: [id] was not found..
        /// </summary>
        public static string CompanyUserWithIdNotFound {
            get {
                return ResourceManager.GetString("CompanyUserWithIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The contract type sent [id] does not found.
        /// </summary>
        public static string ContractTypeNotFound {
            get {
                return ResourceManager.GetString("ContractTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not could convert the string [value] in a list int.
        /// </summary>
        public static string ConvertStringToIntList {
            get {
                return ResourceManager.GetString("ConvertStringToIntList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The country sent does not found.
        /// </summary>
        public static string CountryNotFound {
            get {
                return ResourceManager.GetString("CountryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Daily monitoring has already been created..
        /// </summary>
        public static string DailyTrackingHasAlreadyCreated {
            get {
                return ResourceManager.GetString("DailyTrackingHasAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The specified daily tracking does not exist..
        /// </summary>
        public static string DailyTrackingNotExist {
            get {
                return ResourceManager.GetString("DailyTrackingNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is already a user with this email belonging to this company.
        /// </summary>
        public static string EmailExistsInTheCompany {
            get {
                return ResourceManager.GetString("EmailExistsInTheCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The list of IDs cannot be empty..
        /// </summary>
        public static string EmptyProvidedList {
            get {
                return ResourceManager.GetString("EmptyProvidedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start date is greater than or equal to end date.
        /// </summary>
        public static string EndDateIsInvalid {
            get {
                return ResourceManager.GetString("EndDateIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estimated hours must be greater than zero.
        /// </summary>
        public static string EstimatedHourNotValid {
            get {
                return ResourceManager.GetString("EstimatedHourNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estimated hours exceed the total hours contained in the goal date range..
        /// </summary>
        public static string EstimatedHoursExceedMaximunGoalTime {
            get {
                return ResourceManager.GetString("EstimatedHoursExceedMaximunGoalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect username or password.
        /// </summary>
        public static string FailedLogin {
            get {
                return ResourceManager.GetString("FailedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The text string sent does not follow the correct pattern &quot;1:2,1:3&quot;..
        /// </summary>
        public static string FormatLanguagesIsNotValid {
            get {
                return ResourceManager.GetString("FormatLanguagesIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The goal provided has already been completed. Unable to modify it or add extra miles..
        /// </summary>
        public static string Goal_CompletedAlready_Error {
            get {
                return ResourceManager.GetString("Goal_CompletedAlready_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This Goal is not owned by your user..
        /// </summary>
        public static string Goal_NotOwnedByUser {
            get {
                return ResourceManager.GetString("Goal_NotOwnedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The goal [id] has already been completed and is no longer active..
        /// </summary>
        public static string GoalNotActive {
            get {
                return ResourceManager.GetString("GoalNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The goal [id] was not found..
        /// </summary>
        public static string GoalNotFound {
            get {
                return ResourceManager.GetString("GoalNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The goal [id] does not belong to the provided project..
        /// </summary>
        public static string GoalNotOwnedByProject {
            get {
                return ResourceManager.GetString("GoalNotOwnedByProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The goal status specified not found.
        /// </summary>
        public static string GoalStatus_NotFound {
            get {
                return ResourceManager.GetString("GoalStatus_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The image file is empty.
        /// </summary>
        public static string ImageFileEmpty {
            get {
                return ResourceManager.GetString("ImageFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The order of the specified blocks is not correct, they should be sequential..
        /// </summary>
        public static string InavlidOrderBlockTimeTracking {
            get {
                return ResourceManager.GetString("InavlidOrderBlockTimeTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect current password.
        /// </summary>
        public static string IncorrectCurrentPassword {
            get {
                return ResourceManager.GetString("IncorrectCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The industry sent does not exist.
        /// </summary>
        public static string IndustryNotExist {
            get {
                return ResourceManager.GetString("IndustryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End date must be greater than the start date..
        /// </summary>
        public static string InvalidGoal_EndDateLessThanStarDate {
            get {
                return ResourceManager.GetString("InvalidGoal_EndDateLessThanStarDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The invitation could not be sent.
        /// </summary>
        public static string InvitationNotSent {
            get {
                return ResourceManager.GetString("InvitationNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The job offer sent not found.
        /// </summary>
        public static string JobOfferNotExist {
            get {
                return ResourceManager.GetString("JobOfferNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a there is already a job role category with the name [name].
        /// </summary>
        public static string JobRoleCategoryDuplicated {
            get {
                return ResourceManager.GetString("JobRoleCategoryDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The job role category sent [id] does not found.
        /// </summary>
        public static string JobRoleCategoryNotFound {
            get {
                return ResourceManager.GetString("JobRoleCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a there is already a job role with the name [name].
        /// </summary>
        public static string JobRoleDuplicated {
            get {
                return ResourceManager.GetString("JobRoleDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The job role sent [id] does not found.
        /// </summary>
        public static string JobRoleIdNotFound {
            get {
                return ResourceManager.GetString("JobRoleIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The language level sent [id] does not found.
        /// </summary>
        public static string LanguageLevelNotFound {
            get {
                return ResourceManager.GetString("LanguageLevelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The language sent [id] does not found.
        /// </summary>
        public static string LanguageNotFound {
            get {
                return ResourceManager.GetString("LanguageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account is locked due to too many failed attempts. Please try again after [LockedTimeEnd].
        /// </summary>
        public static string LockedAccount {
            get {
                return ResourceManager.GetString("LockedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is already a settings created for this company.
        /// </summary>
        public static string OneSettingsForCompany {
            get {
                return ResourceManager.GetString("OneSettingsForCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Every attribute has to have a value. The next values were empty or NULL: [emptyProps].
        /// </summary>
        public static string PatchEmptyPropsError {
            get {
                return ResourceManager.GetString("PatchEmptyPropsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The policy sent [id] does not found.
        /// </summary>
        public static string PolicyNotFound {
            get {
                return ResourceManager.GetString("PolicyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The priority level not found..
        /// </summary>
        public static string PriorityLevelNotFound {
            get {
                return ResourceManager.GetString("PriorityLevelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No project accesible for everyone was found..
        /// </summary>
        public static string ProjectAccesibleByEveryoneNotFound {
            get {
                return ResourceManager.GetString("ProjectAccesibleByEveryoneNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The project avatar with ID: [id] was not found..
        /// </summary>
        public static string ProjectAvatarNotFound {
            get {
                return ResourceManager.GetString("ProjectAvatarNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is already a registration with the specified company user..
        /// </summary>
        public static string ProjectCompanyUserDuplicated {
            get {
                return ResourceManager.GetString("ProjectCompanyUserDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is already a registration with the specified company user with the ID: [id]..
        /// </summary>
        public static string ProjectCompanyUserDuplicatedWithId {
            get {
                return ResourceManager.GetString("ProjectCompanyUserDuplicatedWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The project company user with the specified ID was not found: [id]..
        /// </summary>
        public static string ProjectCompanyUserNotFoundWithId {
            get {
                return ResourceManager.GetString("ProjectCompanyUserNotFoundWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The end date should be greater than the start date.
        /// </summary>
        public static string ProjectDatesIncorrect {
            get {
                return ResourceManager.GetString("ProjectDatesIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a there is already a registered project with the name : &quot;[name]&quot;..
        /// </summary>
        public static string ProjectNameDuplicated {
            get {
                return ResourceManager.GetString("ProjectNameDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The project [Name] does not exist or does not belong to the company.
        /// </summary>
        public static string ProjectNotBelongToCompany {
            get {
                return ResourceManager.GetString("ProjectNotBelongToCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No project with the ID: [id] was found..
        /// </summary>
        public static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The specified project does not belong to the company..
        /// </summary>
        public static string ProjectNotOwnedTheCompany {
            get {
                return ResourceManager.GetString("ProjectNotOwnedTheCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The register you are trying to archive, was previously archived..
        /// </summary>
        public static string RegisterAlreadyArchived {
            get {
                return ResourceManager.GetString("RegisterAlreadyArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The register you are trying to unarchive, was previously unarchived..
        /// </summary>
        public static string RegisterAlreadyUnarchived {
            get {
                return ResourceManager.GetString("RegisterAlreadyUnarchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email is not available, please try again..
        /// </summary>
        public static string Result_EmailNotAvailable {
            get {
                return ResourceManager.GetString("Result_EmailNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This email is not associated with any NetForemost account.
        /// </summary>
        public static string Result_EmailNotFound {
            get {
                return ResourceManager.GetString("Result_EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entity [EntityValue] with id [IdValue] does not found..
        /// </summary>
        public static string Result_EntityNotFound {
            get {
                return ResourceManager.GetString("Result_EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thank you for using our services!.
        /// </summary>
        public static string Result_GenericCompletedSecurityProcess_Error {
            get {
                return ResourceManager.GetString("Result_GenericCompletedSecurityProcess_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry an error has occurred, please try again later.
        /// </summary>
        public static string Result_GenericError {
            get {
                return ResourceManager.GetString("Result_GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, something went wrong when [Value]..
        /// </summary>
        public static string Result_GenericSecurity_Error {
            get {
                return ResourceManager.GetString("Result_GenericSecurity_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords must have at least 6 characters, at least one non-alphanumeric character, at least one digit (&apos;0&apos;-&apos;9&apos;) and also have at least one uppercase letter (&apos;A&apos;-&apos;Z&apos;)..
        /// </summary>
        public static string Result_PasswordRules {
            get {
                return ResourceManager.GetString("Result_PasswordRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account has not been verified, please confirm your account first..
        /// </summary>
        public static string Result_ReConfirmAccount {
            get {
                return ResourceManager.GetString("Result_ReConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please reopen the link from your email..
        /// </summary>
        public static string Result_ReOpenFromEmail_Error {
            get {
                return ResourceManager.GetString("Result_ReOpenFromEmail_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your [Value] request has expired, please request the [Value] again..
        /// </summary>
        public static string Result_RequestExpired_Error {
            get {
                return ResourceManager.GetString("Result_RequestExpired_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username is not available, please try again..
        /// </summary>
        public static string Result_UsernameNotAvalaible {
            get {
                return ResourceManager.GetString("Result_UsernameNotAvalaible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account has already been verified before.
        /// </summary>
        public static string Result_VerifiedAccount {
            get {
                return ResourceManager.GetString("Result_VerifiedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The role sent [id] does not found.
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scrum master not found..
        /// </summary>
        public static string ScrumMasterNotFound {
            get {
                return ResourceManager.GetString("ScrumMasterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The ScrumMaster does not participate in this project.
        /// </summary>
        public static string ScrumNotBelongToProject {
            get {
                return ResourceManager.GetString("ScrumNotBelongToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The seniority sent [id] does not found.
        /// </summary>
        public static string SeniorityIdNotFound {
            get {
                return ResourceManager.GetString("SeniorityIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The skill sent [id] does not found.
        /// </summary>
        public static string SkillIdNotFound {
            get {
                return ResourceManager.GetString("SkillIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The story point specified not found..
        /// </summary>
        public static string StoryPointNotFound {
            get {
                return ResourceManager.GetString("StoryPointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account was suspended indeterminately.
        /// </summary>
        public static string SuspendedUser {
            get {
                return ResourceManager.GetString("SuspendedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This talent is already part of the team.
        /// </summary>
        public static string TalentExistsInTheCompany {
            get {
                return ResourceManager.GetString("TalentExistsInTheCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The task with ID: [id] was not found in our records.
        /// </summary>
        public static string TaskNotFound {
            get {
                return ResourceManager.GetString("TaskNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The specified tasks do not belong to the user..
        /// </summary>
        public static string TaskNotOwnToUser {
            get {
                return ResourceManager.GetString("TaskNotOwnToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is already a registered task type with the description: &quot;[description]&quot;..
        /// </summary>
        public static string TaskTypeDescriptionDuplicated {
            get {
                return ResourceManager.GetString("TaskTypeDescriptionDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is already a registered task type with the name : &quot;[name]&quot;..
        /// </summary>
        public static string TaskTypeNameDuplicated {
            get {
                return ResourceManager.GetString("TaskTypeNameDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The task types with IDs: [id] were not found in our records.
        /// </summary>
        public static string TaskTypeNotFound {
            get {
                return ResourceManager.GetString("TaskTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The task type [id] does not belong to the provided project..
        /// </summary>
        public static string TaskTypeNotOwnedByProject {
            get {
                return ResourceManager.GetString("TaskTypeNotOwnedByProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Time block does not belong to the same date as the dailyentry.
        /// </summary>
        public static string TimeBlockNotBelongToDailyEntry {
            get {
                return ResourceManager.GetString("TimeBlockNotBelongToDailyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The time start is greater than time end.
        /// </summary>
        public static string TimeStartIsGreaterThanTimeEnd {
            get {
                return ResourceManager.GetString("TimeStartIsGreaterThanTimeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The start time of the new time block is less than the end time of the last block.
        /// </summary>
        public static string TimeStartIsMinorOfLastTimeEnd {
            get {
                return ResourceManager.GetString("TimeStartIsMinorOfLastTimeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The time zone sent does not exist.
        /// </summary>
        public static string TimeZoneNotExist {
            get {
                return ResourceManager.GetString("TimeZoneNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Specified user not found.
        /// </summary>
        public static string User_NotFound {
            get {
                return ResourceManager.GetString("User_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is already a company created for this account, only one company per account is allowed.
        /// </summary>
        public static string UserAlreadyHaveCompany {
            get {
                return ResourceManager.GetString("UserAlreadyHaveCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, you do not belong to the specified company..
        /// </summary>
        public static string UserDoesNotBelongToTheCompany {
            get {
                return ResourceManager.GetString("UserDoesNotBelongToTheCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This user does not have a company created.
        /// </summary>
        public static string UserHasNotCompany {
            get {
                return ResourceManager.GetString("UserHasNotCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talent cannot be added to your team as it has been locked indefinitely..
        /// </summary>
        public static string UserNotAvailableToAddInTeam {
            get {
                return ResourceManager.GetString("UserNotAvailableToAddInTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user does not participate in this project.
        /// </summary>
        public static string UserNotBelongToProject {
            get {
                return ResourceManager.GetString("UserNotBelongToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The submitted user does not exist.
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This user already has a previously created configuration..
        /// </summary>
        public static string UserSettingsExisting {
            get {
                return ResourceManager.GetString("UserSettingsExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The settings does not exist.
        /// </summary>
        public static string UserSettingsNotExist {
            get {
                return ResourceManager.GetString("UserSettingsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid token.
        /// </summary>
        public static string Validation_InvalidToken_Error {
            get {
                return ResourceManager.GetString("Validation_InvalidToken_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username belongs to the token sent..
        /// </summary>
        public static string Validation_InvalidToken_UserError {
            get {
                return ResourceManager.GetString("Validation_InvalidToken_UserError", resourceCulture);
            }
        }
    }
}
