//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetForemost.SharedKernel.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HtmlTemplatesStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlTemplatesStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetForemost.SharedKernel.Properties.HtmlTemplatesStrings", typeof(HtmlTemplatesStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join!.
        /// </summary>
        public static string Button_Invitation {
            get {
                return ResourceManager.GetString("Button_Invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Account.
        /// </summary>
        public static string ConfirmAccountButtonText {
            get {
                return ResourceManager.GetString("ConfirmAccountButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We are excited for you to start. First, you need to confirm your account. Just click the button below..
        /// </summary>
        public static string ConfirmAccountMainText {
            get {
                return ResourceManager.GetString("ConfirmAccountMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Account.
        /// </summary>
        public static string ConfirmAccountTittle {
            get {
                return ResourceManager.GetString("ConfirmAccountTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thank you for completing the last step, you can now start enjoying all the benefits of the NetForemost application..
        /// </summary>
        public static string ConfirmedAccountHelpText {
            get {
                return ResourceManager.GetString("ConfirmedAccountHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your email has been verified correctly!.
        /// </summary>
        public static string ConfirmedAccountMainText {
            get {
                return ResourceManager.GetString("ConfirmedAccountMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Email.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cheers,&lt;br&gt;NetForemost Team..
        /// </summary>
        public static string EmailClosingText {
            get {
                return ResourceManager.GetString("EmailClosingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you have any questions, just reply to this email&amp;mdash; we&apos;re always happy to help out..
        /// </summary>
        public static string EmailHelpText {
            get {
                return ResourceManager.GetString("EmailHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have been invited to collaborate with [company] through Timeforemost!.
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset Password.
        /// </summary>
        public static string ResetPasswordButtonText {
            get {
                return ResourceManager.GetString("ResetPasswordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A unique link to reset your password has been generated for you. Click on the link below and follow the instructions..
        /// </summary>
        public static string ResetPasswordMainText {
            get {
                return ResourceManager.GetString("ResetPasswordMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset Password.
        /// </summary>
        public static string ResetPasswordTittle {
            get {
                return ResourceManager.GetString("ResetPasswordTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thank you for registering your data, these are now available for all companies that wish to hire your services..
        /// </summary>
        public static string TalentAccountMainText {
            get {
                return ResourceManager.GetString("TalentAccountMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data sent.
        /// </summary>
        public static string TalentAccountTittle {
            get {
                return ResourceManager.GetString("TalentAccountTittle", resourceCulture);
            }
        }
    }
}
